### ISSUE TITLE
how to set position directly instead of update

### ISSUE THREAD

**Issue by lost4git** [clitic/kdam#1]

**Comment by clitic** [comment]
currently no such method to set position. but you can use
`pb.n` to do so.

```rust
use kdam::tqdm;

fn main() {
    let mut pb = tqdm!(total = 50);

    for pos in vec![0, 10, 20, 30, 40, 50] {
        pb.update(pos - pb.n);
    }
}
```

NOTE: overflow error can also be raised.

> thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:7:19

to solve this error type cast `pb.n` as `i64` and finally whole value to `u64`.
