### ISSUE TITLE
`set_total` missing in v0.5

### ISSUE THREAD

**Issue by ShayBox** [clitic/kdam#16]
I need set_total to keep updating the total as I iterate, otherwise I have no total on initialization and have no bar

![image](https://github.com/clitic/kdam/assets/9505196/d3560ddd-4dde-4da7-8ea7-6307cdc39648)

**Comment by clitic** [comment]
`total` field has `pub` visibility. You can directly modify it's value.

https://github.com/clitic/kdam/blob/51e6c7727a9c96750b1add3c4fda24aad80c566a/kdam/src/std/bar.rs#L62

**Comment by ShayBox** [comment]
Oh nice!
