### ISSUE TITLE
Bump pyo3 dependency to 0.20 for Python 3.12 support

### ISSUE THREAD

**Issue by ljeub-pometry** [clitic/kdam#18]
Would it be possible to release a version with the pyo3 dependency bumped to 0.20 which was [released a few weeks ago](https://github.com/pyo3/pyo3/releases)?  

We would like to make use of the new features in 0.20 in [Raphtory](https://github.com/Pometry/Raphtory) but pyo3 does not allow for multiple versions to co-exist in the same crate.

**Comment by clitic** [comment]
@ljeub-pometry I have released kdam [v0.5.1](https://crates.io/crates/kdam/0.5.1) with pyo3 v0.20.

**Comment by miratepuffin** [comment]
Thanks @clitic !
