### ISSUE TITLE
using par_tqdm

### ISSUE THREAD

**Issue by aou** [clitic/kdam#19]
Hello! I am trying to use the `par_tqdm` macro as a manual builder for a bar; can't chain or create with an iterable as the steps I update with are variable in each iteration.

I suspect I'm either using it wrong, or it's not designed for my use-case -- I basically wrap it in an `Arc(Mutex)` and `lock().unwrap().update(some_size)` in the closure.

Is there another way I'm supposed to use it?

Thank you!

**Comment by clitic** [comment]
Currently, this use case is not supported. For now I would suggest you to use `Bar` and manually implement your logic.
