### ISSUE TITLE
Disable postfix stats

### ISSUE THREAD

**Issue by prajnastra** [clitic/kdam#7]
Is there any way to remove `postfix` stats?

**Comment by clitic** [comment]
@prajnastra There is no way to disable postfix stat but you can you use custom bar format. Use this [example]( https://github.com/clitic/kdam/blob/main/examples/template.rs) and edit bar format to.

```
{desc}{percentage:3.0}%|{animation}| {count}/{total} [{elapsed}<{remaining}, {rate:.2}{unit}/s{postfix}]
```

Now remove things which you don't want.
