### ISSUE TITLE
Feature request: Support Jupyter notebooks

### ISSUE THREAD

**Issue by igiloh-pinecone** [clitic/kdam#8]
One of the most common uses for `tqdm` is within Jupyter notebooks.  
It doesn't seem that `kdam` is supporting that use case properly for the moment.

**Comment by clitic** [comment]
I haven't tried [evcxr_jupyter](https://crates.io/crates/evcxr_jupyter) but I think it's integration for custom message can be used to achieve this feature. I will give it a try and update you.
