### ISSUE TITLE
Support for various contrib modules from tqdm

### ISSUE THREAD

**Issue by akshettrj** [clitic/kdam#9]
In addition to terminal progress bars, tqdm also supports displaying progress bars in various other platforms which can be found [here](https://github.com/tqdm/tqdm/tree/master/tqdm/contrib).

Is it possible to support other platforms in kdam as well?

Or is there any guide for contributors for creating such modules on our own?

**Comment by clitic** [comment]
I have noted down your points and realized that some works needs to be done before using kdam in external crate to implement custom bars. Firstly, I have made some `Bar` fields public and changed functions visibility to `pub`. Secondly, I have renamed `_impl_bar_methods!` to `derive_bar_ext`. I would do more changes before releasing it to crates.io. Till then you try `main` branch.

**Comment by clitic** [comment]
Now you an use kdam in external crate. [example](https://github.com/clitic/kdam/blob/160dcc201e7b29acadbbf7d32bdb5f1c8b72d584/examples/miscellaneous/custom.rs)
